### ISSUE TITLE
Package Overlaps

### ISSUE THREAD

**Issue by alexanderigeorgiev** [CID15/aem-groovy-console#11]
Hello,
We are using groovy console version 17.0.0 on AEM as a Cloud Service.
The pipeline execution includes some code scanning and one of its findings is this one:

File: org.cid15.aem.groovy.console:aem-groovy-console-ui.config:17.0.0
Issue: affected path /apps/groovyconsole/osgiconfig overlaps [aem-groovy-console:aem-groovy-console-ui.apps:17.0.0]
Adobe rule Package Overlaps is explained here https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html?lang=en#oakpal-no-overlap (https://www.adobe.com/go/aem_cmcq_packageoverlaps_en)

In summary two packages aem-groovy-console-ui.config and aem-groovy-console-ui.apps are both writing to /apps/groovyconsole/osgiconfig. That should not happen.

Is is possible that this is fixed in some of the upcoming releases?

**Comment by Narendiran100** [comment]
Any update on this

**Comment by kwin** [comment]
You should consider switching to the maintained fork at https://github.com/orbinson/aem-groovy-console/tree/main which has this issue (and several others) fixed.

**Comment by alexanderigeorgiev** [comment]
Switching to version 19.0.4 of be.orbinson.aem is fixing the package
overlaps issue

**Comment by markdaugherty** [comment]
Fixed in 18.0.0
